/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Control;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dipta
 */
public class MScreen extends javax.swing.JFrame {
    public String Gender;
    public String Religion;
    public String nameStart;
    public String nameContain;
    public String nameEnd;
    
    /**
     * Creates new form MScreen
     */
    public MScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JCgender = new javax.swing.JComboBox();
        JCreligion = new javax.swing.JComboBox();
        JCnameStart = new javax.swing.JComboBox();
        JCnameContain = new javax.swing.JComboBox();
        JCnameEnd = new javax.swing.JComboBox();
        JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BanglaNameMaker");
        setBounds(new java.awt.Rectangle(300, 150, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel.setBackground(new java.awt.Color(204, 204, 204));
        jPanel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 41)); // NOI18N
        jLabel1.setText("BANGLA  NAME  MAKER");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Gender");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("First Letter");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Mid Letter");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Last Letter");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Religion");

        JCgender.setBackground(new java.awt.Color(204, 204, 255));
        JCgender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JCgender.setForeground(new java.awt.Color(51, 51, 51));
        JCgender.setMaximumRowCount(4);
        JCgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));
        JCgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCgenderActionPerformed(evt);
            }
        });

        JCreligion.setBackground(new java.awt.Color(204, 204, 255));
        JCreligion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JCreligion.setForeground(new java.awt.Color(51, 51, 51));
        JCreligion.setMaximumRowCount(4);
        JCreligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Religion", "Christian", "Hindu", "Muslim" }));
        JCreligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCreligionActionPerformed(evt);
            }
        });

        JCnameStart.setBackground(new java.awt.Color(204, 204, 255));
        JCnameStart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JCnameStart.setForeground(new java.awt.Color(51, 51, 51));
        JCnameStart.setMaximumRowCount(4);
        JCnameStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Letter", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        JCnameStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCnameStartActionPerformed(evt);
            }
        });

        JCnameContain.setBackground(new java.awt.Color(204, 204, 255));
        JCnameContain.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JCnameContain.setForeground(new java.awt.Color(51, 51, 51));
        JCnameContain.setMaximumRowCount(4);
        JCnameContain.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Letter", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        JCnameContain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCnameContainActionPerformed(evt);
            }
        });

        JCnameEnd.setBackground(new java.awt.Color(204, 204, 255));
        JCnameEnd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JCnameEnd.setForeground(new java.awt.Color(51, 51, 51));
        JCnameEnd.setMaximumRowCount(4);
        JCnameEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Letter", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        JCnameEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCnameEndActionPerformed(evt);
            }
        });

        JButton.setBackground(new java.awt.Color(51, 51, 255));
        JButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JButton.setForeground(new java.awt.Color(255, 255, 255));
        JButton.setText("GENERATE");
        JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JCreligion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCgender, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCnameStart, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCnameContain, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCnameEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(129, 129, 129))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCreligion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(JCnameStart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JCnameContain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JCnameEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JCgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCgenderActionPerformed

    private void JCreligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCreligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCreligionActionPerformed

    private void JCnameStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCnameStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCnameStartActionPerformed

    private void JCnameContainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCnameContainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCnameContainActionPerformed

    private void JCnameEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCnameEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCnameEndActionPerformed

    private void JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonActionPerformed
        Gender         = JCgender.getSelectedItem().toString();
        Religion        = JCreligion.getSelectedItem().toString();
        nameStart      = JCnameStart.getSelectedItem().toString();
        nameContain  = JCnameContain.getSelectedItem().toString();
        nameEnd       = JCnameEnd.getSelectedItem().toString();
        
        // All combination are true
        if (!Gender.equalsIgnoreCase("Select gender")) {
            if (!Religion.equalsIgnoreCase("Select religion")) {
                if (!nameStart.equalsIgnoreCase("Select a letter")) {
                    if (!nameContain.equalsIgnoreCase("Select a letter")) {
                         if (!nameEnd.equalsIgnoreCase("Select a letter")) {
                             
                             String EBname[][] = new String[500][2];
                             String CONname[][] = new String[500][2];
                             String ENDname[][] = new String[500][2];
                             String COMMname[][] = new String[500][2];
                             Control control = new Control(Gender, Religion, nameStart, nameContain, nameEnd);
                             String sourcePath = control.SourceFilePath();
                             
                             try {
                                 control.BNMnames(sourcePath, EBname, CONname, ENDname, COMMname, nameContain, nameEnd);
                                 
                             } catch (FileNotFoundException ex) {
                                 Logger.getLogger(MScreen.class.getName()).log(Level.SEVERE, null, ex);
                             }
                             
                             int index = 1;
                             int num = 2;
                             if (control.commonindex >= 1) {
                                SHscreen shs = new SHscreen(COMMname, control.commonindex);
                                shs.setVisible(true);
                             } else if (control.endindex >= 1) {
                                SHscreen shs = new SHscreen(ENDname, control.endindex);
                                shs.setVisible(true);
                             } else if (control.containindex >= 1) {
                                 SHscreen shs = new SHscreen(CONname, control.containindex);
                                 shs.setVisible(true);
                             } else {
                                 SHscreen shs = new SHscreen(EBname, control.nameindex);
                                 shs.setVisible(true);
                             }
                             
                             
                             /*
                             System.out.println(control.nameindex);
                             for (int i=0; i<control.nameindex; i++) {
                                     System.out.println(EBname[i][0] + "  " + EBname[i][1]);
                              } */
                             
                         } else {
                             System.out.println("F5");
                         }
                    } else {
                        System.out.println("F4");
                    }
                } else {
                    System.out.println("F3");
                }
            } else {
                System.out.println("F2");
            }
        } else {
            System.out.println("F1");
        }
        
    }//GEN-LAST:event_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JButton;
    public static javax.swing.JComboBox JCgender;
    public static javax.swing.JComboBox JCnameContain;
    public static javax.swing.JComboBox JCnameEnd;
    public static javax.swing.JComboBox JCnameStart;
    public static javax.swing.JComboBox JCreligion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
